
# Molecular topology
charges:
  T: 0.0  # Terminal bead
  H: 0.0  # Head bead
  B: 0.0  # Body bead

# Force field parameters
bonds:
  style: harmonic
  k: 300.0
  r0: 1.0

angles:
  style: harmonic
  k: 500.0
  theta0: 180.0

pair:
  style: lj/cut
  cutoff: 2.5
  epsilon: 1.0
  sigma: 1.0
  shift: "yes"
  wca_cutoff: 1.122

# Integration parameters
timestep: 0.001
bead_volume: PI/6

# Minimization
minimization:
  etol: 1.0e-4
  ftol: 1.0e-6
  maxiter: 100
  maxeval: 1000

# Phase transition protocol
pressure: 1.0

prod_cycles: 20      # Number of production cycles

# Output control
thermo_freq: 1000
dump_freq: 10000
restart_freq: 50000

# LAMMPS variables to be protected from being replaced by template
cycle: ${cycle}     

# Annealing for phase transitions
annealing:
  iso:
    temp: 2.0
    steps: 500000
    temp_damp: 0.1
    press_damp: 100.0
  stage1:
    temp: 1.2
    steps: 500000
    temp_damp: 1.0
    press_damp: 100.0
  stage2:
    temp: 1.0
    steps: 500000
    temp_damp: 5.0
    press_damp: 100.0
  final:
    temp: 0.5
    steps: 2000000
    temp_damp: 10.0
    press_damp: 100.0

production:
  temp: 0.5
  npt_steps: 100000    
  nvt_steps: 32000   
  2pt_freq: 16
  temp_damp: 10.0      
  press_damp: 100.0    # Keep pressure coupling constant 