# Molecular topology
charges:
  T: 0.0    # Terminal bead
  H: 0.0    # Head bead
  B: 0.0    # Body bead

# Force field parameters
bonds:
  style: harmonic
  k: 300.0
  r0: 1.0

angles:
  style: harmonic
  k: 500.0
  theta0: 180.0

pair:
  style: lj/cut
  cutoff: 2.5
  epsilon: 1.0
  sigma: 1.0
  shift: "yes"
  wca_cutoff: 1.122

# System parameters
system:
  timestep: 0.001
  bead_volume: PI/6
  pressure: 1.0
  tempinit: 0.1

# Minimization settings
minimization:
  etol: 1.0e-4
  ftol: 1.0e-6
  maxiter: 100
  maxeval: 1000

# Output control
output:
  thermo_freq: 1000
  dump_freq: 10000
  restart_freq: 50000
  prod_cycles: 20    # Number of production cycles

# Annealing protocol (total steps = 15M)
annealing:
  step0:    # Low T compression
    temp: 0.1
    steps: 500000      
    temp_damp: 0.1         
    press_damp: 1.0  
  
  step1:    # Heat
    temp: 2.0
    steps: 100000      
    temp_damp: 1.0      
    press_damp: 1.0     
  
  step2:    # Hold
    temp: 2.0
    steps: 1000000      
    temp_damp: 0.1      
    press_damp: 1.0     

# Production run parameters
production:
  temp: 0.2     
  npt_steps: 100000     
  nvt_steps: 32000      
  2pt_freq: 16
  temp_damp: 1.0      
  press_damp: 10.0    # Keep pressure coupling constant

# LAMMPS variables to be protected from template replacement
protected_vars:
  cycle: $cycle
  T: $T
  Tstart: $Tstart
  Tend: $Tend
  Tstep: $Tstep
  loop: $loop 
  pe_diff: $pe_diff